title: Tom's blog
description: >-
  This is a place for me to blog about random things that I find interesting, or 
  things that I think can help other people out.
url: "https://thomasquirke.com"
github_username:  tdq132

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
